OnlineLearningSystem/OnlineLearningSystem.MVC/Controllers/ContactController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineLearning.BL.DTOs;
using OnlineLearning.BL.Services.Abstractions;
using System.Security.Claims;

namespace OnlineLearningSystem.MVC.Controllers;

public class ContactController : Controller
{
	readonly IContactService _service;
    readonly ICourseService _courseService;
    readonly IMapper _mapper;
    public ContactController(IContactService service, IMapper mapper, ICourseService courseService)
    {
        _service = service;
        _mapper = mapper;
        _courseService = courseService;
    }
	public async Task<IActionResult> Index()
	{
		var course = await _courseService.GetCourseListItemsAsync();
		ViewData["Course"] = new SelectList(course, "Id", "CourseName");

		return View();
	}
	[HttpGet]
	public async Task<IActionResult> Create()
	{
		var courses = await _courseService.GetCourseListItemsAsync();
		ViewData["Courses"] = new SelectList(courses, "Id", "CourseName");

		return View();
	}


	[HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ContactDTO dto)
    {
        if (!User.Identity.IsAuthenticated)
        {
            return Unauthorized();
        }



        if (!ModelState.IsValid)
        {
            return RedirectToAction("Index", "Home");
        }

		await _service.UserCreateAsync(dto,
            User.Identity.Name
        );
        await _service.SaveChangesAsync();

        TempData["SuccessMessage"] = "Your message has been submitted successfully!";
        return RedirectToAction("Index", "Home");
    }
}

OnlineLearningSystem/OnlineLearningSystem.MVC/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineLearning.BL.Services.Abstractions;
using OnlineLearning.Core.Models;
using OnlineLearningSystem.MVC.ViewModels;

namespace OnlineLearningSystem.MVC.Controllers
{
    public class CourseController : Controller
    {
        readonly ITeacherService _teacherService;
        readonly ICourseService _courseService;

        public CourseController(ITeacherService teacherService, ICourseService courseService)
        {
            _teacherService = teacherService;
            _courseService = courseService;
        }

        public async Task<IActionResult> Index(string searchTerm, int page = 1, int pageSize = 10, string sortBy = "CourseName")
        {
            try
            {
                var courses = await _courseService.SearchCoursesAsync(searchTerm, page, pageSize, sortBy);

                HomeVM VM = new()
                {
                    Teachers = await _teacherService.GetTeacherViewItemsAsync(),
                    Courses =  await _courseService.GetCourseViewItemsAsync()
                };

                ViewData["Courses"] = VM.Courses;

                return View(VM);
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong!");
            }
        }

        [HttpGet]
        public async Task<IActionResult> SearchCourses(string searchTerm, int page = 1, int pageSize = 10)
        {
            if (page < 1 || pageSize < 1)
            {
                return BadRequest("Səhifə dəyəri düzgün deyil");
            }

            var courses = await _courseService.SearchCoursesAsync(searchTerm, page, pageSize);

            return Ok(courses);
        }
    }
}

OnlineLearningSystem/OnlineLearningSystem.MVC/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineLearning.BL.Services.Abstractions;
using OnlineLearning.Core.Models;

namespace OnlineLearning.User.Controllers
{
    public class PaymentController : Controller
    {
        private readonly IStripeService _stripeService;

        public PaymentController(IStripeService stripeService)
        {
            _stripeService = stripeService;
        }

        [HttpPost]
        public async Task<IActionResult> CreateCheckoutSession(Payment paymentSession)
        {
            if (paymentSession == null)
            {
                return View("Error"); // Error view if paymentSession is null
            }

            var sessionUrl = await _stripeService.CreateCheckoutSessionAsync(paymentSession);
            return Redirect(sessionUrl); // Redirect to Stripe checkout session URL
        }

        public IActionResult PaymentSuccess()
        {
            return View(); // Success view
        }

        public IActionResult PaymentCancel()
        {
            return View(); // Cancel view
        }
    }
}

OnlineLearningSystem/OnlineLearningSystem.MVC/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineLearning.BL.Services.Abstractions;
using OnlineLearningSystem.MVC.ViewModels;

namespace OnlineLearningSystem.MVC.Controllers;

public class TeacherController : Controller
{
	readonly ITeacherService _teacherService;
	readonly ICourseService _courseService;
	public TeacherController(ITeacherService teacherService, ICourseService courseService)
	{
		_teacherService = teacherService;
		_courseService = courseService;
	}
	public async Task<IActionResult> Index()
	{
		try
		{
			HomeVM VM = new()
			{
				Teachers = await _teacherService.GetTeacherViewItemsAsync(),
				Courses = await _courseService.GetCourseViewItemsAsync()
			};


			return View(VM);
		}
		catch (Exception)
		{
			return BadRequest("Something went wrong!");
		}
	}
}

OnlineLearningSystem/OnlineLearningSystem.MVC/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>SiteName - Dashboard</title>

	<!-- Custom fonts for this template-->
	<link href="~/admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
		  rel="stylesheet">

	<!-- Custom styles for this template-->
	<link href="~/admin/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

	<!-- Page Wrapper -->
	<div id="wrapper">

		<!-- Sidebar -->
		<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

			 <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Dashboard" asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">LearningSystem</div>
            </a>

			<!-- Divider -->
			<hr class="sidebar-divider my-0">

			<!-- Nav Item - Dashboard -->
			<li class="nav-item active">
				<a class="nav-link" asp-controller="Dashboard" asp-action="Index">
					<i class="fas fa-fw fa-tachometer-alt"></i>
					<span>Dashboard</span>
				</a>
			</li>
			<!-- Divider -->
			<hr class="sidebar-divider">

			<!-- Heading -->
			<div class="sidebar-heading">
				Interface
			</div>

			<!-- Nav Item - Tables -->
			<li class="nav-item">
				<a class="nav-link" asp-controller="Teacher" asp-action="Index">
					<i class="fas fa-fw fa-table"></i>
					<span>Teachers</span>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" asp-controller="Student" asp-action="Index">
					<i class="fas fa-fw fa-table"></i>
					<span>Students</span>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" asp-controller="Course" asp-action="Index">
					<i class="fas fa-fw fa-table"></i>
					<span>Courses</span>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" asp-area="Admin" asp-controller="Payment" asp-action="Index">
					<i class="fas fa-fw fa-table"></i>
					<span>Payment</span>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" asp-controller="Statistics" asp-action="Index">
					<i class="fas fa-fw fa-table"></i>
					<span>Statistics</span>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" asp-controller="Contact" asp-action="Index">
					<i class="fas fa-fw fa-table"></i>
					<span>Contact</span>
				</a>
			</li>
			<!-- Divider -->
			<hr class="sidebar-divider d-none d-md-block">

			<!-- Sidebar Toggler (Sidebar) -->
			<div class="text-center d-none d-md-inline">
				<button class="rounded-circle border-0" id="sidebarToggle"></button>
			</div>

		</ul>
		<!-- End of Sidebar -->
		<!-- Content Wrapper -->
		<div id="content-wrapper" class="d-flex flex-column">

			<!-- Main Content -->
			<div id="content">

				<!-- Topbar -->
				<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

					<!-- Sidebar Toggle (Topbar) -->
					<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
						<i class="fa fa-bars"></i>
					</button>

					<!-- Topbar Navbar -->
					<ul class="navbar-nav ml-auto">

						<!-- Nav Item - User Information -->
						<li class="nav-item dropdown no-arrow">
							<a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
							   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<span class="mr-2 d-none d-lg-inline text-gray-600 small">UserName</span>
								<img class="img-profile rounded-circle" src="~/admin/img/undraw_profile.svg">
							</a>
							 <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
						</li>

					</ul>

				</nav>
				<!-- End of Topbar -->
	@RenderBody()
			  <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; OnlineLearningSystem @DateTime.Now.Year </span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
				<!-- End of Footer -->

			</div>
			<!-- End of Content Wrapper -->

		</div>
		<!-- End of Page Wrapper -->
		<!-- Scroll to Top Button-->
		<a class="scroll-to-top rounded" href="#page-top">
			<i class="fas fa-angle-up"></i>
		</a>

		<!-- Logout Modal-->
		<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
			 aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
						<button class="close" type="button" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">×</span>
						</button>
					</div>
					<div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
				 <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" asp-area="Admin" asp-controller="Account" asp-action="Logout">Logout</a>
                </div>
				</div>
			</div>
		</div>

		<!-- Bootstrap core JavaScript-->
		<script src="~/admin/vendor/jquery/jquery.min.js"></script>
		<script src="~/admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

		<!-- Core plugin JavaScript-->
		<script src="~/admin/vendor/jquery-easing/jquery.easing.min.js"></script>

		<!-- Custom scripts for all pages-->
		<script src="~/admin/js/sb-admin-2.min.js"></script>
</body>

</html>